version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ionicons
    versions:
    - 5.4.0
    - 5.5.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: admin-lte
    versions:
    - 3.0.5
